Update sr

diff --git a/sr b/sr
--- a/sr
+++ b/sr
@@ -1,83 +1,76 @@
 #!/bin/bash
 : '
-	Interactive linux utility to search and replace text inside files inside a directory
+	Linux utility to recursively search and replace text inside files 
+
+        - Recursively search for text inside files
+        - Search all files with the input file extension
+        - The tool follows symbolic link and update the actual file
+        - No backup file will be created, It is the responsibility of the user to take a backup
+	- Recursively search all th sub directories
+
+    Useful for:
+
+        - Web Site Admin
+        - System Admin
+
 
 
 	Author   : Viki (a) Vignesh Natarajan
 	Contact  : vikiworks.io  
 '
 
+S="$1"
+R="$2"
+E="$3"
 
-if [ -z "$1" ]; then
-    echo "usage: sr <search_string> <replace_string> <file_name/ wildcard file names>"
-    echo 
-    echo "example: sr foo bar "*.html"" 
-    echo 
-    exit 1
-fi
+function usage(){
+    echo "Usage : $0 <search string> < replace string > <File Extension, .php, .txt etc>"
+}
 
-if [ -z "$2" ]; then
-    echo "usage: sr <search_string> <replace_string> <file_name/ wildcard file names>"
-    echo 
-    echo "example: sr foo bar "*.html"" 
-    echo 
-    exit 1
-fi
-
-if [ -z "$3" ]; then
-    echo "usage: sr <search_string> <replace_string> <file_name/ wildcard file names>"
-    echo 
-    echo "example: sr foo bar "*.html"" 
-    echo 
-    exit 1
-fi
-
-
-
-SEARCH_STRING="$1"
-REPLACE_STRING="$2"
-args=( $@ )
-
-echo
-echo "    search pattern  ( $SEARCH_STRING  )"
-echo "    replace pattern ( $REPLACE_STRING )"
-echo 
-
-i=0
-hit=0
-n_args_to_skip=2
-for file in "${args[@]}"
-do
-    if [ $i -lt $n_args_to_skip ]; then
-        i=$((i+1))
-	continue
+function input_validation(){
+    if [ -z "$S" ]; then
+        usage
+        exit 1
     fi
 
-    grep $SEARCH_STRING $file 1> /dev/null 2> /dev/null
-    if [ $? -ne 0 ]; then 
-        #echo "Search string not available at ( $file )"
-        continue
+    if [ -z "$R" ]; then
+        usage
+        exit 1
     fi
-    
-    hit=1
 
-    read -p "    Do you want to execute search-replace operation on ( $file ) ? " -n 1 -r
-    if [[ ! $REPLY =~ ^[Yy]$ ]]
-    then
-       echo
-       echo "    Skipping search and replace operation on ($file)"
-       echo
-       continue
+    if [ -z "$E" ]; then
+        usage
+        exit 1
     fi
+}
+
+function print_info(){
+    echo
+    echo " Search String  : $S"
+    echo " Replace String : $R"
+    echo " File Extension : $E"
+    echo
+}
+
+function user_confirmation(){
+    echo
+    read -p " Do you want to recursively search and replace? ( Y/N )" -n 1 -r
     echo
 
-        vim -c "%s/$SEARCH_STRING/$REPLACE_STRING/gc" -c 'wq' $file
-    
-done
+    if [[ ! $REPLY =~ ^[Yy]$ ]]
+    then
+        echo " note:   abort search and replace operation"
+        exit 1
+    fi
+}
 
-if [ $hit -eq 0 ]; then
-    echo " no files with requested search pattern found"
-fi
-echo
+function search_n_replace(){
+	find . -type f -name "*${E}"  | while read -r file; do echo "S [ $S ] R [ $R ] F [ $file ]"; sed -i --follow-symlinks -e "s/$S/$R/g" "$file";done
+}
 
+input_validation
+print_info
+# You can comment user_confirmation if you don't need it
+user_confirmation
+search_n_replace
 
